import React, { useCallback, useState, useEffect } from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import HeadC from "../components/Head";
import { RoomsService } from "../services/Rooms.service";
import Body from "../components/Body";

export default function Home() {
  useEffect(async () => {
    console.log("Obteniendo datos de la api");

    RoomsService.getMarkers("madrid").then(
      (markers) => {
        console.log(markers);
      },
      (error) => {
        seterrorServer(true);
      }
    );
  }, []);
  return (
    <div className={styles.container}>
      <Head>
        <title>HomeSales</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/home.ico" />
      </Head>

      <main className={styles.main}>
        <HeadC />
        <Body />
      </main>

      <footer className={styles.footer}>
        © 2017 CLICASA. TODOS LOS DERECHOS RESERVADOS Mapa web Contacto Aviso
        Legal
        <Image
          src={"/assets/1489335132-facebook-circle-color.svg"}
          alt="facebook"
          width={30}
          height={30}
        />
        <Image
          src={"/assets/1489335133-twitter-circle-color.svg"}
          alt="twitter"
          width={30}
          height={30}
        />
        <Image
          src={"/assets/1489335130-linkedin-circle-color.svg"}
          alt="lidkelin"
          width={30}
          height={30}
        />
        <Image
          src={"/assets/1489335135-youtube-circle-color.svg"}
          alt="youtube"
          width={30}
          height={30}
        />
      </footer>
    </div>
  );
}
