import React, { useCallback, useState, useEffect } from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import HeadC from "../components/Head";
import { RoomsService } from "../services/Rooms.service";

export default function Home() {
  useEffect(async () => {
    console.log("Obteniendo datos de la api");

    RoomsService.getMarkers("madrid").then(
      (markers) => {
        console.log(markers);
      },
      (error) => {
        seterrorServer(true);
      }
    );
  }, []);
  return (
    <div className={styles.container}>
      <Head>
        <title>HomeSales</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/home.ico" />
      </Head>

      <main className={styles.main}>
        <HeadC />
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
